### ISSUE TITLE
Monitor the number of games and players

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_game_engine#108]
We should be able to monitor how many games with how many players are going on at any given time, possibly also historically. This will require the ability to distinguish ongoing games from finished or inactive ones.
This doesn't call for a full dashboard, but at the very least the ability to query the current status.

**Comment by maciej-pomykala** [comment]
A game could have a 'last queried' field and / or a 'last changed' field.
Any measure of inactivity would be probably based on one / both of those and the game status.
