### ISSUE TITLE
Set up Dev deployment CI

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_game_engine#121]
Merges to develop should deploy the current version automatically to the currently configured Dev port.
Merges to master should deploy stable releases automatically to a designated Prod port with a fixed version URL (v2 _not_ v2.2). Clients should be using the prod deployment. The prod deployments (whether v2, v2.1, v2.2...) need to not introduce compatibility breaking changes (instead move to v3).

Set up a Github action for Dev deployments triggered on merges to develop.

**Comment by maciej-pomykala** [comment]
Is it separate from #53 ?

**Comment by adrian-golian** [comment]
> Is it separate from #53 ?

Noope... Duplicate. Would you mind if we close #53, since there's more content here?

**Comment by maciej-pomykala** [comment]
Closed

**Comment by adrian-golian** [comment]
(Marked as "duplicate")
