### ISSUE TITLE
Create version endpoint

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_game_engine#131]
Create an endpoint at the path: `http://localhost:8000/v2/version`
Method: GET
Response:
{"version": "2.3.4"}

Also, replace minor version with major version in the URL path (not `/v2.2`, but '/v2/'.

**Comment by maciej-pomykala** [comment]
This issue includes making a test for that endpoint.

**Comment by adrian-golian** [comment]
...and update CI to run it ater a deployment.

**Comment by adrian-golian** [comment]
The test for this has to go to a new issue - too much interdependency / sequentiality among current PRs.
