### ISSUE TITLE
Clean public games periodically

### ISSUE THREAD

**Issue by maciej-pomykala** [Blef-team/blef_game_engine#170]
We need to prevent the queries of public games from DynamoDB from consuming too much data.

We already make games private when they begin.

However, we should also have a Lambda function that gets triggered on a regular schedule (say, every 30 minutes) and privatises games that are public but have been inactive for a long time (say, last modified longer than 30 minutes ago).

**Comment by adrian-golian** [comment]
I believe this is made obsolete by one of the later commits in #169

**Comment by maciej-pomykala** [comment]
I think it's not, actually. 
We stopped displaying those games by filtering the results of the query we make for public games. But they are still public and we just filter them using `FilterExpression`, which means that the query still accesses them, but just doesn't return them to us. 
When we make those games public they will be outside of the `KeyConditionExpression`, which is when they finally won't be accessed by the query and won't impose costs on us.
