### ISSUE TITLE
Implement rate limiting

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_game_engine#28]
Especially since some endpoints can be successfully interacted with by just knowing the path (/create), a proper rate limiting needs to be implemented. We still want valid usage to be possible at a high rate, but spam/abuse/DDoS needs to be prevented.

**Comment by maciej-pomykala** [comment]
Also, once we design and let design AIs, which will probably have an 'invite to game' and 'invite to make move' endpoint, we will have to prevent people from spamming games with somebody else's AIs.

**Comment by maciej-pomykala** [comment]
[This](https://d1.awsstatic.com/whitepapers/Security/DDoS_White_Paper.pdf) will be possibly a good source on DDoS protection on AWS

**Comment by maciej-pomykala** [comment]
What do you think of "Fix \#3" [here](https://making.pusher.com/per-ip-rate-limiting-with-iptables/)?

As I understand, we could apply this policy to the whole EC2 instance, making it impossible for someone to use any interface deployed on the instance to attack the engine (without botnets and other toys).

**Comment by adrian-golian** [comment]
Fix # 3 sounds good - let's try it out on the instance.

**Comment by maciej-pomykala** [comment]
We implemented:
```
$ sudo iptables --append RATE-LIMIT \
    --match hashlimit \
    --hashlimit-mode srcip \
    --hashlimit-upto 50/sec \
    --hashlimit-burst 20 \
    --hashlimit-name conn_rate_limit \
    --jump ACCEPT
$ sudo iptables --append RATE-LIMIT --jump DROP
```
...and it seems to work. We're closing the issue.
