### ISSUE TITLE
Document the API schema

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_game_engine#3]
Create `api/README.md` with the API documentation, following this format: https://gist.github.com/iros/3426278

**Comment by adrian-golian** [comment]
While we're at it, let's update the `api/README.md` to explain `action_id` and make it explicit and clear that it is the _set seniority_ - core to the game logic.

_Originally posted by @adrian-golian in https://github.com/Blef-team/blef_game_engine/issues/37#issuecomment-612442179_

**Comment by maciej-pomykala** [comment]
Have a look at what I've commited and let me know if any comments

**Comment by adrian-golian** [comment]
All looks good, apart from section [Action]
