### ISSUE TITLE
Fix /games/{id} returning 500

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_game_engine#31]
`/v1/games/xyz` responds with a `500 - Internal server error` rather than inform you that the provided string is not a valid UUID.
- check whether game_uuid is in fact a UUID before trying to find a game on the server
- if it isn't, return an appropriate response code and message

**Comment by adrian-golian** [comment]
Having played a game to the end, after the game finishes, this is the response of the endpoint:
```
{
    "message": "The UUID does not match any player"
}
```

**Comment by maciej-pomykala** [comment]
These are two different things. 
I fixed the first. 
The `"The UUID does not match any player"` is factually correct, because the game forgets players who are no longer active. Would you like the message modified to make it more precise?

**Comment by adrian-golian** [comment]
It's that if I give it a UUID that does not match any player, it gives me 500.
If I give it a UUID that does in fact match a player, but the game is finished, then it doesn't give me the 500 anymore.

**Comment by maciej-pomykala** [comment]
I can't really replicate this issue. It gives me `"The UUID that does not match any player"` when I input a nonsensical UUID

**Comment by adrian-golian** [comment]
<img width="468" alt="Screenshot 2020-04-12 at 01 00 29" src="https://user-images.githubusercontent.com/10632991/79056664-0a99b300-7c59-11ea-9676-57ccda55763c.png">

**Comment by adrian-golian** [comment]
> Having played a game to the end, after the game finishes, this is the response of the endpoint:
> 
> ```
> {
>     "message": "The UUID does not match any player"
> }
> ```

Sorry, I think I got confused about the issues. #31 is about a non-existing game UUID.

**Comment by adrian-golian** [comment]
Basically, to fix, add UUID validation.

**Comment by maciej-pomykala** [comment]
I believe this has been solved. Close or let me know if any problems.

**Comment by adrian-golian** [comment]
Tested with HEAD at `develop` (335e717) - fixed. Closing.
