### ISSUE TITLE
Fix /games/{id} returning 500 if player UUID provided and game not started

### ISSUE THREAD

**Issue by maciej-pomykala** [Blef-team/blef_game_engine#34]
If a player provides their UUID (a valid one, in contrast to #31) the game returns an error code 500.

**Comment by maciej-pomykala** [comment]
I believe I solved this.
However, I think we have to think about something else here:

- should players be able to explicitly query the 0th round when the game is not yet started
- should players be able to explicitly query the 0th round when the game is has already started (in which case we'll need to save a snapshot)

**Comment by adrian-golian** [comment]
I think we both agree now that there's no information to query in round 0 (that isn't also by definition in round 1).

**Comment by maciej-pomykala** [comment]
As discussed, I'll fix the error instead in the `jsonise_hands` function
