### ISSUE TITLE
Add action_id and description to indexation.csv

### ISSUE THREAD

**Issue by maciej-pomykala** [Blef-team/blef_game_engine#37]
Make the `action_id` to `hand_type` and `detail` fixed, by explicitly storing action_ids in `indexation.csv`.
Make use of the coupling in `/games/{id}/play` endpoint code and anywhere else that might be consuming `indexation.csv`.
Add a `description` field to `indexation.csv` and serve this information in the response of `/games/{id}`, in the `history` key.

**Comment by adrian-golian** [comment]
While we're at it, let's update the `api/README.md` to explain `action_id` and make it explicit and clear that it is the set seniority - core to the game logic.

**Comment by adrian-golian** [comment]
Decided with @maciej-pomykala against a description field.
