### ISSUE TITLE
Allow optional parameters in /games/{id}/play

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_game_engine#41]
Requires #37 
Since the coupling between `action_id` and `hand_type` and `detail` is fixed in `indexation.csv`, we can allow callers of `/games/{id}/play` to identify their moves with a combination `hand_type` and `detail`.
This will require move validation - checking with `indexation.csv` whether the move is legal and can be assigned an action_id.
This will also require revision of the standardisation of the strings in "hand_type" - perhaps snake_case / camelCase.

**Comment by maciej-pomykala** [comment]
We concluded that the play endpoint will only accept the `action_id`

Instead, attached to the endpoints documentation there will be a clear table outlining what each `action_id` represents. This will make things fairly comfortable for the occasional person who wants to play through Postman & co.

The code will continue to rely on the separate `indexation.csv`.

**Comment by maciej-pomykala** [comment]
Requesting closure of the issue
