### ISSUE TITLE
Put input validation in all endpoints

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_game_engine#43]
Besides fixing #31, #32 and #34, let's ensure all endpoints validate all request parameter values before executing.

**Comment by maciej-pomykala** [comment]
Once we settle the UUIDs I'll assign myself and do that.

I know what to do with action IDs and rounds. But we'll have to discuss what nicknames are allowed.

**Comment by adrian-golian** [comment]
This is a good start:
```
^[a-zA-Z]\w*$

```
https://stackoverflow.com/a/22836617

**Comment by maciej-pomykala** [comment]
#65 does almost all of the needed work here, but I'll add the nickname acceptability check
