### ISSUE TITLE
In the current game state, mention players who have already lost

### ISSUE THREAD

**Issue by maciej-pomykala** [Blef-team/blef_game_engine#56]
Currently, the get state endpoint of the API does not mention players who were playing in the game but have lost. It would be nicer if it did.

The players will be listed with `n_cards = 0`

As discussed on our call.

**Comment by maciej-pomykala** [comment]
I will not be reporting the dropped out players' hands (empty arrays) in the `hands` object. 

Let me know if you disagree

**Comment by adrian-golian** [comment]
Ok, just a sanity check.
What is the API, without our a priori interpretation, actually telling us if we do this?
It says, there are (e.g.) 5 players, 2 of whom are dealt cards this round - (e.g.) 4 and 6, while 3 of them got dealt nothing this round.
Does that unequivocally communicate that they are out of the game? I think it does. Agree?

**Comment by maciej-pomykala** [comment]
When we want to know something fundamental about players, we look into `players`.
The content of `hands` depends on what we are authorised to see, so we are not really expecting it to tell us meaningful things using `hands`

**Comment by maciej-pomykala** [comment]
I think that yes, it does unequivocally communicate that these people are out of the game.

**Comment by maciej-pomykala** [comment]
When I'm thinking about whether the API unequivocally communicates that these players are out of the game, I think it does, but under the condition that we are not expecting it to be hiding things away from us because of privacy issues.

**Comment by adrian-golian** [comment]
Yeah, I think what's in `hands` is fine either way. The `players` object's telling us clearly that those players have 0 cards. Non `"hidden"`, not `null`, not `-1` but `0`. This seems fine.
