### ISSUE TITLE
Refactor code so that checks for errors do not indent the rest of the code

### ISSUE THREAD

**Issue by maciej-pomykala** [Blef-team/blef_game_engine#61]
Current `if` and `else` statements reduce clarity

**Comment by adrian-golian** [comment]
Instead of this:
```
if (!checkA & !checkB & !checkC) {
  core function code
}
else if (checkA)  errorA
else if (checkB) errorB
else if (checkC) errorC
```
do
```
if (checkA) errorA
if (checkB) errorB
if (checkC) errorC
core function code
```
_Originally posted by @adrian-golian in https://github.com/Blef-team/blef_game_engine/pull/60#issuecomment-615933859_

**Comment by adrian-golian** [comment]
Btw, there are some weird things happening in [`endpoints.R`]https://github.com/Blef-team/blef_game_engine/blob/9cc0062754d68e0353b2a80e4e8c5e4498eae475/api/endpoints.R#L164):
```
    game_path <- get_path(game_uuid)
    
    if(file.exists(game_path)) {
      current_r <- readRDS(game_path)$round_number
      if (round == -1 | round == current_r) {
        r <- current_r
        game <- readRDS(get_path(game_uuid))
      } else {
        r <- as.numeric(round)
        game <- readRDS(get_path(game_uuid, r))
      }
```
Why assign `game_path` when you're not using it. You can just do `file.exists(get_path(game_uuid))`

**Comment by maciej-pomykala** [comment]
From what I udnerstand, you would have been pleased to look at [this commit](https://github.com/Blef-team/blef_game_engine/commit/7430e9050e55a85d03d3205c8d00bed5a323c9c7)
