### ISSUE TITLE
Fix 500 status codes in deployment

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_game_engine#78]
The current state the service, up-to-date with `develop`, tested on EC2, seems to have issues writing/reading data on the machine. This could be to do with the move of `game_data` to `~`.

This is the observed behaviour:
```
$ curl $GAMEENGINEAPIURL/games/baf1fd82-5beb-45a1-8165-54b78853a6df
{"error":"Game does not exist"}
$ curl $GAMEENGINEAPIURL/games/create
{"error":"500 - Internal server error"}
$ curl $GAMEENGINEAPIURL/games
{"error":"500 - Internal server error"}
```

**Comment by maciej-pomykala** [comment]
For now i can confirm that this is happening and that it gets fixed by killing the R process initiated by automatic deployment and executing `run_api.R` manually.

**Comment by maciej-pomykala** [comment]
I think the R console output can be [written to a file](https://stackoverflow.com/questions/53486153/how-to-write-console-output-to-a-text-file-with-rscript-like-you-can-with-r-cmd), but I think that trying this solution out would involve pushing test code to master...

**Comment by adrian-golian** [comment]
Yeah, we should be capturing the logs either way. I’ll do that and redeploy manually.

**Comment by adrian-golian** [comment]
Ok.
1. Redeploying `develop` seems to have fixed this issue. We should figure out what could've been going on though, if possible.
2. Logging's added as part of a new issue (#79)

We should close this.

**Comment by maciej-pomykala** [comment]
Ok, I'm fine with closing
