### ISSUE TITLE
Fix no response to join attempt with special characters

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_game_engine#84]
Observed behaviour:
```
$ curl <BASE PATH>/games/ab0adc2c-28a4-4f54-9652-ff6156277507/join?nickname=Xylophonic_Xólotl
curl: (52) Empty reply from server
```

**Comment by maciej-pomykala** [comment]
The function does not get executed at all. I'm trying to find a solution for this, but it's taking a few moments so far.

**Comment by adrian-golian** [comment]
This is probably not an error with the game engine. I can call this endpoint like this, successfully:
```
curl -i -X GET -Ht=ISO-8859-1" <BASE PATH>/games/ab0adc2c-28a4-4f54-9652-ff6156277507/join? --data-ascii "nickname=Xylophonic_Xólotl"
```

**Comment by adrian-golian** [comment]
Opened Blef-team/blef_ios_app#28 to handle this issue.
If you agree, we can close this.

**Comment by maciej-pomykala** [comment]
I have been able to transform the problem into the (possibly less disturbing) problem present in [this link](https://github.com/rstudio/plumber/issues/153) by using percent encoding - that is, `Xólotl` becomes `X%C3%B3lotl`.

**Comment by maciej-pomykala** [comment]
But the latter problem is Windows-specific so I agree that, long story short, we can close this issue.

**Comment by adrian-golian** [comment]
Closing.
